### ISSUE TITLE
Unit test / edge case checklist (2020/04)

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#155]
Miscellaneous unit tests and edge cases which aren't covered by other issues. Might split some of these off into their own issues later.

- accounts
  - [x] login: Test redirect after login
  - [x] profile list: Test pagination
- annotations
  - annotation tool: Load the annotation form on the annotation tool page...
    - [x] with blank annotations
    - [x] with all unconfirmed annotations
    - [x] with all confirmed annotations (should show 'All Done')
    - [x] with some annotations confirmed, some blank
    - [x] with some annotations confirmed, some unconfirmed
    - [x] each of the above with 'show machine annotations' setting on or off
  - [x] annotation tool: Load the settings form and ensure the user's saved values are present
  - [x] save annotations ajax: Save annotations after changing some from unconfirmed to confirmed
  - [x] is annotation all done ajax: If some are unconfirmed, should not be all done
  - annotation area edit
    - [x] Load a percentage based annotation area
    - [x] Load a pixel based annotation area
    - [x] Submit an edited annotation area
  - point generation
    - [x] Stratified random and uniform grid, not just simple random.
- Browse Images
  - [x] Handling of invalid search parameters
  - [x] Correct indication of image statuses (border color, or presence of CSS class)
  - Asychronous generation of thumbnails as needed (probably needs some Selenium tests)
    - [x] Load thumbnails which already exist
    - [x] Generate thumbnails which don't exist yet
- [x] Image real-filename generation (for saving to S3): ensure no two images can have the same filename. Test by replacing the filename generation function (using Mocker?) with something that only can generate a few unique filenames.
- [x] Caching of label popularity. Fetch the popularity once, then replace the full popularity implementation with something that raises an error, then fetch popularity again.

**Comment by StephenChan** [comment]
Going to tackle some of these items soon and leave others for later.

**Comment by StephenChan** [comment]
Okay, time to clean this up. Here are the items I'm discarding or putting off for now:

>       * annotation area edit
>         * QUnit tests
>           * [ ]  Change each of the 4 text fields
>           * [ ]  Drag the resize handles; ensure the drag extremities are where they should be
>           * [ ]  Text field errors: non-integers, beyond min/max, min greater than max

Moved to issue #305.

>       * point generation
>         * [ ]  Unusual annotation areas: min and max very close or the same, and decimal percentages.
>         * [ ]  Ensure no two points are at the same pixel location. If impossible, should return an appropriate error. One test: 4x5 image with 20 points should have no two points at the same location.

First one: I tested decimal percentages. Min and max very close or the same doesn't seem like it'd trigger any interesting code paths, and it's not much of a use case anyway, as far as I know.

> 
>     * Browse Images
>       * Asychronous generation of thumbnails as needed (probably needs some Selenium tests)
>         * [ ]  Poll the server multiple times until generation is complete

Moved to issue #305.
 
>     * [ ]  Submission of vision backend tasks upon events like image upload and image-status confirmed. Might need to make the backend more easily testable first.

Do after issue #264.

>     * [ ]  Dates, user timezones, and DST. Dates to check include: image upload date, source create date, annotation history dates. Check annotation dates in exported CSVs also.

I don't think our date behavior is that well-defined in the first place. Moved to issue #306.

>     * [ ]  Maintenance message tests

Currently, a test for this would write to the non-test location for the maintenance-status file, since tests don't define a `SITE_DIR` setting value separate from non-test environments. So I'd prefer to do issue #307 first.

**Comment by beijbom** [comment]
Thanks for the break-down @StephenChan . Looks like you have a good handle on what we can defer, and what needs to be done for each item. I added a comment on the duplicate row/col location issue.

**Comment by beijbom** [comment]
@StephenChan : should we close this and mark as done in project?

**Comment by StephenChan** [comment]
Yeah, just wanted to make sure the unit-test PR was good to go. Same goes for #54 and #157.
